### ISSUE TITLE
is self contained installation possible?

### ISSUE THREAD

**Issue by noname77** [mongodb-labs/mongo-arrow#110]
Hi,

I am using this package in a docker environment with a multistage build, i.e. I am building all python dependancies to a virtual environment in a build stage and copying it to the final production image.

I was hoping `pymongoarrow` would be self contained, i.e. it would not require any additional apt-get installs in the production image.

However, when attempting to use pymongoarrow in the production image I am getting:

```
/opt/venv/lib/python3.9/site-packages/pymongoarrow/__init__.py:34: UserWarning: Could not find compiled pymongoarrow.lib extension, please install from source or report the following traceback on the issue tracker:
Traceback (most recent call last):
  File "/opt/venv/lib/python3.9/site-packages/pymongoarrow/__init__.py", line 32, in <module>
    from pymongoarrow.lib import libbson_version
ImportError: libbson-1.0.so.0: cannot open shared object file: No such file or directory

  warnings.warn(
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)

(...)

    from pymongoarrow.api import Schema
  File "/opt/venv/lib/python3.9/site-packages/pymongoarrow/api.py", line 26, in <module>
    from pymongoarrow.context import PyMongoArrowContext
  File "/opt/venv/lib/python3.9/site-packages/pymongoarrow/context.py", line 16, in <module>
    from pymongoarrow.lib import (
ImportError: libbson-1.0.so.0: cannot open shared object file: No such file or directory
```

here are the contents of `pymongoarrow` site-package
```
$ ls -l /opt/venv/lib/python3.9/site-packages/pymongoarrow/
total 68624
-rw-r--r-- 1 user user     1606 Nov 23 17:16 __init__.py
drwxr-xr-x 2 user user      267 Nov 23 17:16 __pycache__
-rw-r--r-- 1 user user    13902 Nov 23 17:16 api.py
-rw-r--r-- 1 user user     3456 Nov 23 17:16 context.py
-rw-r--r-- 1 user user     1553 Nov 23 17:16 errors.py
-rwxr-xr-x 1 user user  2400424 Nov 23 17:16 lib.cpython-39-aarch64-linux-gnu.so
-rw-r--r-- 1 user user    13466 Nov 23 17:16 lib.pyx
-rw-r--r-- 1 user user     1232 Nov 23 17:16 libarrow.pxd
-rwxr-xr-x 1 user user 56618568 Nov 23 17:16 libarrow.so.900
-rwxr-xr-x 1 user user  2251680 Nov 23 17:16 libarrow_python.so.900
-rw-r--r-- 1 user user     3960 Nov 23 17:16 libbson.pxd
-rwxr-xr-x 1 user user  8915624 Nov 23 17:16 libparquet.so.900
-rw-r--r-- 1 user user     1484 Nov 23 17:16 monkey.py
-rw-r--r-- 1 user user      945 Nov 23 17:16 result.py
-rw-r--r-- 1 user user     2397 Nov 23 17:16 schema.py
-rw-r--r-- 1 user user     4465 Nov 23 17:16 types.py
-rw-r--r-- 1 user user      637 Nov 23 17:16 version.py
```

I need to install the `libbson` library explicitly with
```
sudo apt-get update && sudo apt-get install libbson-1.0-0
```
then everything is working as expected.

Is this a bug or a feature?

Best,
Wiktor

**Comment by blink1073** [comment]
Hi @noname77, our built wheels include `libbson`, and our `conda-forge` recipe depends on the `libbson` conda package, but if you're building from source, then yes, you will need to either install `libbson` from your package manager, or use our [build-libbson.sh](https://github.com/mongodb-labs/mongo-arrow/blob/main/bindings/python/build-libbson.sh) script to build from GitHub source.

**Comment by noname77** [comment]
Thank you,

is there a plan to build and publish wheels for aarch64 architecture?

**Comment by blink1073** [comment]
I created https://jira.mongodb.org/browse/ARROW-131
